version: '3.3'

services:
  web:
    build: ./container-web/
    ports:
      - "6900:6970"
    networks:
      - microweb 
    container_name: microweb_web
  api:
    build: ./container-api
    networks:
      - microweb
    container_name: microweb_api

networks: 
  microweb:
